apiVersion: v1
kind: Secret
metadata:
  name: azure-file-share
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  azurestorageaccountname: {{ .Values.storageAccount.name  }}
  azurestorageaccountkey: {{ .Values.storageAccount.key  }}
